# NPRE 100: Introduction to Python 

### Drs. Madicken Munk and April Novak


Welcome to NPRE 100, Introduction to Python! Programming is an important skill you will continually build during your undergraduate program. In this lesson, you will learn:
- Basic syntax of Python
- How to find and use modules
- How to use functions, loops, and more
- How to make plots

### How to Use Jupyter Notebooks

This lesson is designed using Jupyter Notebooks, a web-based interactive computing platform. In this notebook, you will see a number of "cells" (gray boxes) where you will be writing Python code. Here are some tips for using Jupyter notebook:

- To run each code cell, type "Shift+Enter". You can also click in the toolbar "Cell" -> "Run Cells"
- To add a cell below your current cell, press "Esc+b".
- To run all code cells up to and including the current cell, click in the toolbar "Cell" -> "Run All Above"
- To run all code cells, click in the toolbar "Cell" -> "Run All"

Some of the cells you will see contain text instead of Python code. This text is formatted in "Markdown." If you want to add a text cell, type "Esc+m" to convert a cell into Markdown (text) form.

In the NPRE 100 in-person class, we launched a Jupyter notebook using Binder. 
<span style="background-color: #FFFF00">But for your assignment, please be sure to either [launch Jupyter notebook from the command line/terminal/shell](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/execute.html) or work in a Python script file! Any work you do in the Binder will not be saved once you leave the Binder instance.</span>

### Programming: the coolest calculator you'll ever have. And it's free! 

What are some operators you'd expect to see on a calculator? Addition? subtraction? Multiplication and division? 

In [118]:
3*4

12

12

In [119]:
4-3

1

In [ ]:
2+3

In [ ]:
1/2

We can also print useful messages in our scripts that make things more readable

In [ ]:
print("Hello world!")

Another useful feature of Python, like all programming languages, is "comments" - lines you can add to your code which do not get executed, typically used to document and explain the code. In Python, single-line comments begin with `#`.

In [ ]:
# This is a comment
print("I love NPRE") # This is also a comment

A comment does not always need to be text describing the code - it can be used to prevent a code line from executing

In [ ]:
#print("hmmmm")

New lines are very important in Python - every line in a Python program is interpreted as an instruction. In other programming languages, such as C++, instructions are instead denoted using some symbol at the end of each instruction (such as a `;`). If you want to write an instruction over multiple lines, you will need to use a special character, `\`.

In [ ]:
# Python will try to run this as two instructions, but the formatting is not quite right, so you will get an error!
print("This is a longer message which is so long
that I want it to extend over multiple lines")

In [ ]:
# Instead, use \ to indicate a line break
print("This is a longer message which is so long \
that I want it to extend over multiple lines")

Indentation is also very important in Python - it is used to define something called "scope," when you are "inside" functions, loops, classes, etc. In other programming languages, spaces are often used just for clarity.

In [ ]:
print("hi")
  print("there")

Words, numbers, and calculations are useful, but what’s more useful are the sentences and stories we build with them. Similarly, while a lot of powerful, general tools are built into Python, specialized tools built up from these basic units live in libraries that can be called upon when needed.

Importing a library is like getting a piece of lab equipment out of a storage locker and setting it up on the bench. Libraries provide additional functionality to the basic Python package, much like a new piece of equipment adds functionality to a lab space. Just like in the lab, importing too many libraries can sometimes complicate and slow down your programs - so we only import what we need for each program.

### How to figure out what libraries to import?

With so many users and developers of Python around the world, there are many many libraries available. One way to search for a desired feature is via Google or your favorite search engine. For example, if I would like a library which can sample random numbers for me, I would first try googling "python random number generator." Another way to search is through the [Python Package Index](https://pypi.org). 

In [125]:
import Joking

In [126]:
print(Joking.random_dad_joke())

My boss told me that he was going to fire the person with the worst posture. I have a hunch, it might be me.


In [127]:
# These are a few more useful packages we'll be using today in this lesson
import numpy as np 
import matplotlib.pyplot as plt
import math

### Using Modules

So what does this give us? Well, we have a huge amount of knowledge at our fingertips that we don't need to program any more! And it's written by experts. 

Modules contain variables, functions, and classes - to access them, you will need to use a period (`.`) between the module name you imported, and the variable/function/class you want to access. For instance, `math.pi` will use the variable `pi` in the `math` module.

In [ ]:
# let's print the value of pi from the math module
print(pi)

When using variables/functions/classes, remember that we need to insert a `.` between the module name and the variable/function/class. In the whole wide world of Python, it's impossible to guarantee that there will only be one single `pi` variable defined across all modules in existence - so to avoid clashes, we need to use a `.` to indicate that we are referring to `pi` from the `math` library.

In [ ]:
# This is the correct way to get the pi variable from the math library
print(math.pi)

In [ ]:
# let's see if we just let whatever is returned from a function 
# be returned in the notebook. Maybe exp()? 
math.exp(2.0)

ok! I've convinced you that there are some useful things that you can do. Let's go over some Python basics to get you all started

### Variables

You just saw me do some small calculations with Python, but what if I want to save information to use later? We do that using **variables**. To create a variable in python, we use an equals sign. The characters to the left are the name of the variable, and the expression on the right is its value. 

In [ ]:
# create a variable called `my_variable`
my_variable = 3

In [ ]:
# print the variable
print(my_variable)

From now on, when I call `my_variable` with Python, it knows to return the value of the variable. That is, 3.0. 

In Python, variable names:

* can include letters, digits, and underscores
* cannot start with a digit
* are case sensitive.

But be careful! We can easily overwrite variables too. What happens if I assign a new value to a variable with the same name? 

In [ ]:
my_variable

In [ ]:
my_variable = 6
my_variable

# Discussion: What do you think this means when you choose to name your variables? 

Use meaningful names that are detailed enough to not conflict with other variables in your program.

We can also perform operations on variables: 

In [ ]:
# make a new variable and print both
another_variable = 1
print(another_variable)
print(my_variable)

Or even modify a variable in place:

In [ ]:
# add a variable in place to `my_variable`
my_variable = my_variable + another_variable

In [ ]:
# now let's print the new value of `my_variable`
my_variable

# Data Types in Python 

ok! So now we know how to do some simple operations and store some of our computations as variables. However, there have been a few different things we've seen. Letters and numbers. 

In [ ]:
# Strings can be defined using either single or double quotes
my_variable = 'I love cats!'
print(my_variable)

In [ ]:
type(my_variable)

In [ ]:
# Strings can be defined using either single or double quotes
my_variable = "I love cats!"
print(my_variable)

In [ ]:
my_variable = "April's favorite season is fall"
print(my_variable)

In [ ]:
# Integers
my_variable = 345
type(my_variable)

In [ ]:
# Floats
my_variable = 1.23
type(my_variable)

In [ ]:
# Booleans (true or false)
my_variable = True
type(my_variable)

In Python, you can change the "type" of a variable after you've already set it to some other type. Above, we defined `my_variable` to be a string, then changed it to an integer, then changed it to a float.


### Some Built-In Collections

Python contains many other data types aside from the basics of strings, booleans, floats, etc. Let's explore lists, dictionaries, sets, and tuples -- types used to store collections of data. Below is a summary of the important characteristics of these built-in collection types.

|                    | Lists     | Dictionaries                 | Sets      | Tuples    |
|--------------------|-----------|------------------------------|-----------|-----------|
| Ordered?           | Yes       | No                           | No        | Yes       |
| Changeable?        | Yes       | Yes                          | No        | No        |
| Duplicate members? | Yes       | No                           | No        | Yes       |
| Syntax             | [a, b, c] | {key1: value1, key2: value2} | {a, b, c} | (a, b, c) |


Let's start with lists, which are used to store multiple values into a single variable. They are *ordered*, changeable, and allow multiple types and repeated values. Lists are created using square brackets.

In [ ]:
# Lists (can be comprised of integers, floats, strings, bools)
my_list = ["apple", "uranium", 2.5, 3]

In [ ]:
# Lists can be accessed with the index. Let's see what the value of 
# the 0th item in the list is
my_list[0]

In [ ]:
my_list[1]

In [ ]:
my_list[2]

In [ ]:
# We can change the value of an entry in a list
my_list[1] = "plutonium"
print(my_list)

In [ ]:
# We can add entries to a list (note that we are adding a duplicate entry!)
my_list.append("plutonium")
print(my_list)

In [123]:
# We can get the length of a list
print(len(my_list))

4


In [ ]:
# We can also remove items from a list
my_list.pop(2)
print(my_list)

Dictionaries are used to store data in key, value pairs. They are ordered, changeable, and do not allow duplicates. Dictionaries are created using curly brackets, using a comma-separated series of key, value pairs.

In [88]:
# dictionaries
uranium_dictionary = {"isotopes" : [233, 235, 238], \
                     "year_discovered" : 1789, \
                     "dollars_per_kg" : 135.3}

In [89]:
print(uranium_dictionary)

{'isotopes': [233, 235, 238], 'year_discovered': 1789, 'dollars_per_kg': 135.3}


In [92]:
# We just talked about accessing with a list. What do you think 
# accessing with a dict looks like? 
print(uranium_dictionary["isotopes"])

[233, 235, 238]


In [93]:
print(uranium_dictionary["isotopes"][1])

235


In [95]:
# Let's change the value of the `dollars_per_kg` key
uranium_dictionary["dollars_per_kg"] = 125.9
print(uranium_dictionary)

{'isotopes': [233, 235, 238], 'year_discovered': 1789, 'dollars_per_kg': 125.9}


Sets are used to store collections of data which are unordered and do not allow repeated entries. Sets are also created using curly brackets, but are different from dictionaries in that they do not use key, value pairs.

In [97]:
months = {"January", "February", "March"}

In [98]:
print(months)

{'February', 'January', 'March'}


In [100]:
# Sets cannot be changed after they are created
months.append("April")

AttributeError: 'set' object has no attribute 'append'

In [103]:
# Duplicate entries are not allowed
my_set = {1, 2, 5, 1}
print(my_set)

{1, 2, 5}


### Arrays

Python does not have a built-in array data type, but Python lists can be used instead. But, they are slow to process and don't have all the convenience features we may want. 

Instead, you can use an array type defined by the `numpy` library. `numpy` is short for "numerical Python," and contains many useful features for arrays (as well as lots of other useful functionality for linear algebra, matrices, and more).

In [128]:
# our first numpy array
my_array = numpy.array([1, 3, 5, 7])

NameError: name 'numpy' is not defined

In [134]:
# Don't forget that we imported the numpy module under a shorthand name, np. This is called an "alias"
my_1d_array = np.array([1, 3, 5, 7])
print(my_1d_array)

[1 3 5 7]


To create a numpy array, we can pass a list, tuple, or other array-type object to `np.array()`. Above, we used a list. Numpy arrays can be of different "dimensions" - 0D arrays (scalars), 1D arrays (vectors), 2D arrays (tensors), etc.

In [132]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_2d_array)

[[1 2 3]
 [4 5 6]]


In [133]:
my_0d_array = np.array(9)
print(my_0d_array)

9


Accessing entries in a numpy array is similar to accessing entries in a list.

In [135]:
print(my_1d_array[1])

3


In [138]:
print(my_2d_array[1,0])

4


We can use negative indices to access an array "backwards."

In [139]:
print(my_1d_array)

[1 3 5 7]


In [140]:
print(my_1d_array[-1])

7


In [141]:
print(my_1d_array[-2])

5


We can also "slice" into an array, to extra multiple entries at the same time. The syntax is `start:stop:step`, where this will fetch all items beginning at index `start`, ending at `stop` (but not inclusive of `stop`), with `step` increments taken between each.

In [144]:
my_slice = my_1d_array[0:2]
print(my_slice)

[1 3]


In [147]:
my_slice = my_1d_array[-3:-1]
print(my_slice)

[3 5]


Slicing in higher-dimensional arrays can also be performed. Let's try to get the second column in our 2-D array. A `:` is used to indicate "all values" in that particular dimension.

In [148]:
print(my_2d_array)

[[1 2 3]
 [4 5 6]]


In [149]:
my_slice = my_2d_array[:, 1]
print(my_slice)

[2 5]


# Discussion: Why do you think different types of data exist in Python? Can you see how you would use each kind? 

# Python Operators

### Now that you've seen some different types of objects in Python, let's explore the different types of operations you can do on them. 

Arithmetic Operators: 
* addition   a + b
* subtraction a - b
* multiplication   a*b 
* division a/b 
* modulus   a%b
* exponent a**b 

In [ ]:
10**2

In [ ]:
10%3

Comparison Operators:

    * equal == 
    * not equal != 
    * greater than > 
    * less than <
    * greater than or equal to >=
    * less than or equal to <=

In [ ]:
9/3 == 3

In [ ]:
10/3 == 3

Logical Operators:
    
    * and ( inclusion of both )
    * or ( one or other )
    * not ( cannot include ) 

# Python Conditionals 

### Now that we've learned about different operators in Python, let's consider what it would look like to combine them with conditional statements in python. Some examples of conditionals are:
* if .... else
* while
* for 

Let's see some examples of each. 

In [ ]:
a = 20
b = 30 
if a > b:
    print('a is greater than b')
else:
    print('a is less than b')

In [ ]:
year = 1990
while year < 1999:
    print(f"The year is {year}. Let's party like it's 1999!")
    year += 1 

# Discussion: what happens if the condition of the while loop is not met? 

In [ ]:
for x in range(2,6):
    print(x)

We can combine logic however we want! 

In [ ]:
for x in range(70,100,5):
    if x < 85:
        print(f"My grade is {x} and it is below the class average")
    elif x == 85:
        print(f"I have the same grade as the class average!")
    else:
        print(f"My grade is {x} and it is above the class average")

# Introduction to Functions

Another type of object in Python is something called a function. A function takes **arguments** and performs a task on them. That function can then be called to perform the same operation over and over again. To write a function, we have to **define** it with a specific convention. 

In [ ]:
type(3.0)

In [ ]:
def add_two_numbers(a, b):
    """
    Returns the value of variables a and b
    
    Parameters
    ----------
    a: int or float
    b: int or float
    
    Returns:
    sum_both: int or float 
        The sum of both variables
    
    """
    sum_both = a+b  # here is where I perform the sum
    return sum_both

Here we have defined a function called **add_two_numbers**, where two variables **a** and **b** are passed into it. When the function is called, it adds a and b together, and then returns that value. Let's see how well it works!

Note also I have multiple types of documentation in this function. A **docstring** and an **inline comment**. 


# Checkpoint: Why do I want multiple types of documentation? Why do I want documentation at all?

In [ ]:
add_two_numbers(10,20)

In [ ]:
print(add_two_numbers.__doc__)

In [ ]:
add_two_numbers(50,60)

What happens to the variable stored in the function? 

In [ ]:
sum_both

In the Python language there are a huge number of functions built in to help you write your programs. I recommend searching for them in the documentation to learn about how to use them. Some very common functions you will enounter are:
* type()
* abs()
* sum()
* max()
* len()

In [ ]:
# Let's try an example!!! 
len('NPRE is cool')

In [ ]:
# Pro-tip: you can always check the documentation of a function in a notebook with the question mark
np.arange?

In [ ]:
np.arange(1,10,2)

In [ ]:
# What do you think our previous function looks like with this feature?
print(add_two_numbers.__doc__)

# Arrays 

### Ok, let's get used to array computations since you'll use them a LOT in NE. 

### First we'll create a random 10x10 matrix

In [ ]:
our_data = np.random.randint(10, size=100).reshape(10,10) 
our_data

![](https://swcarpentry.github.io/python-novice-inflammation/fig/python-zero-index.svg)

If we want to get a specific value on the matrix we need to do a selection. Since this matrix is 2d we need to specify the row it is in, and the column it is in. So, let's try a few selections:

In [ ]:
our_data[3][2]

In [ ]:
our_data[3]

In [ ]:
our_data[1][1]

We cam also use the `:` to do larger selections. So to take the 2nd column we would do:

In [ ]:
our_data[:,1]

In [ ]:
our_data[0:2,0:2]

In [ ]:
our_data[:2,:2]

In [ ]:
our_data[-5:,-5:]

In [ ]:
print(np.max(our_data))
print(np.min(our_data))
print(np.std(our_data))

# Checkpoint: using np.max() to get the maximum value in an array, find the maximum value in each row of your data matrix.

![](https://swcarpentry.github.io/python-novice-inflammation/fig/python-zero-index.svg)

# Plotting

### Earlier we imported a module from matplotlib called pyplot. This is the object-oriented interface for matplotlib's plotting tools. There are so many ways you can create and modify plots with this interface. 

Resources: 
[matplotlib gallery](https://matplotlib.org/stable/gallery/index.html)
![](https://matplotlib.org/stable/_images/sphx_glr_anatomy_001.png)

In [ ]:
#first we define our x and y points:
x = np.linspace(0,10, num=1000, endpoint=True)
y = np.sin(x*3+x**2+2)

In [ ]:
plt.plot(x,y,'-')
plt.legend(['function'], loc='best')
plt.show()

Oh no! But there is no title or axes for this plot? How can we fix it? 

In [ ]:
plt.plot(x,y,'-')
plt.legend(['function'], loc='best')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Plot of our cool function')
plt.savefig('our_plot.png')

Pro-tip: Check out all of the plot objects that are available to you via tab completion. 

# Bringing it all together

In [ ]:
from scipy.interpolate import interp1d

In [ ]:
# first we'll define our x and y points 
x = np.linspace(0, 10, num=11, endpoint=True)
y = np.cos(-x**2/9.0)

In [ ]:
# now we'll use scipy's interpolate routine to get a few interpolations of this data 
f = interp1d(x, y)
f2 = interp1d(x, y, kind='cubic')
f3 = interp1d(x, y, kind='quadratic')

In [ ]:
# now let's plot it! 
xnew = np.linspace(0, 10, num=41, endpoint=True) # this defines more points for the interpolations
plt.plot(x, y, 'o', xnew, f(xnew), '-', xnew, f2(xnew), '--', xnew, f3(xnew), '-*')
plt.legend(['data', 'linear', 'cubic', 'quadratic'], loc='best')
plt.show()

### Some useful Python packages for your work:

* matplotlib [docs](https://matplotlib.org/) [source](https://github.com/matplotlib/matplotlib)
* numpy [docs](https://numpy.org/doc/stable/) [source](https://github.com/numpy/numpy)
* scipy [docs](https://scipy.org/scipylib/) [source](https://github.com/scipy/scipy)
* sympy [docs](https://docs.sympy.org/latest/index.html) [source](https://github.com/sympy/sympy)
* pytest [docs](https://docs.pytest.org/en/6.2.x/) [source](https://github.com/pytest-dev/pytest)
* unyt [docs](https://unyt.readthedocs.io/en/stable/) [source](https://github.com/yt-project/unyt)
* pyne [docs](http://pyne.io/) [source](https://github.com/pyne/pyne)
* radioactivedecay [docs](https://radioactivedecay.github.io/) [source](https://github.com/radioactivedecay/radioactivedecay)
* serpenttools [docs](https://serpent-tools.readthedocs.io/en/latest/) [source](https://github.com/CORE-GATECH-GROUP/serpent-tools)
* shabblona [source](https://github.com/uwescience/shablona)

### Final Discussion:

There are many versions of Python that exist, and many versions of packages that exist. What does that mean for your work? 

# Happy Pythoning!!! 

In [ ]:
import antigravity